apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.networking.cafebazaar.cloud/load-balancer: zooket-nginx-cdn
    cloud.networking.cafebazaar.cloud/load-balancer-external-ip: zooket-nginx-cdn-lb
  name: {{ include "nginx-cdn.fullname" . }}
  labels:
    {{- include "nginx-cdn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-cdn.selectorLabels" . | nindent 4 }}
